### ISSUE TITLE
Attempting user-token authentication results in an error: 'You must authenticate to access this resource.'

### ISSUE THREAD

**Issue by jfindlay** [discogs/discogs_client#58]
I am trying to follow the quickstart guide in the README but am running into problems trying to use the user token.  I don't know why the version says `2.0.2`, but this is from the HEAD of master.
```python
>>> import discogs_client
>>> discogs_client.__version__
u'2.0.2'
>>> d = discogs_client.Client('JMoney/0.1', token="...")
>>> results = d.search('Stockholm By Night', type='release')
>>> results.pages
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "discogs_client/models.py", line 336, in pages
    self._load_pagination_info()
  File "discogs_client/models.py", line 297, in _load_pagination_info
    data = self.client._get(self._url_for_page(1))
  File "discogs_client/client.py", line 123, in _get
    return self._request('GET', url)
  File "discogs_client/client.py", line 120, in _request
    raise HTTPError(body['message'], status_code)
discogs_client.exceptions.HTTPError: 401: You must authenticate to access this resource.
>>> 
```

**Comment by jfindlay** [comment]
I am wrong.  This is a user error.  I was originally using the version of the client that ships with gentoo, 2.0.2, in which `discogs_client.Client` does not have a `user_token` keyword argument.  If I replace `user=` with `user_token=`, everything seems to work as expected.
